
""" 
NEURON — SYNAPSE PARAMETERS, EVENT TIMING, AND EXCITATION/INHIBITION

This lesson studies:
    nc.weight[0]
    nc.delay
    nc.threshold
    stim.number
    stim.start
    stim.interval
    syn.e = 0
    syn.e = -80

Basic architecture:

    NetStim
       |
       | event
       v
    NetCon
       |
       | delay + weight
       v
    ExpSyn
       |
       | synaptic current
       v
    neuron membrane

CONCEPTUAL ROLES
----------------
NetStim = creates artificial events
NetCon  = transmits events; can add delay and weight
ExpSyn  = converts an arriving event into a conductance change
Neuron  = converts synaptic current into a voltage response
"""

from neuron import h
import matplotlib.pyplot as plt

h.load_file("stdrun.hoc")

# ============================================================
# 1. Simple Passive Neuron (only somma)
# ============================================================

soma = h.Section(name="soma")
soma.L = 20
soma.diam = 20
soma.nseg = 1

soma.insert("pas")
soma.Ra = 100
soma.cm = 1
soma.g_pas = 0.0001
soma.e_pas = -65

# ============================================================
# 2. ExpSyn: CREATE ARTIFICIAL SYNAPSE
# ============================================================

syn = h.ExpSyn(soma(0.5))

syn.tau = 2 # time constant of the synaptic conductance decay

syn.e = 0 # reversal potential of the synapse (excitatory)
# At V ~ -65 mV:
#   e = 0   -> depolarizing/excitatory
#   e = -80 -> hyperpolarizing/inhibitory

# ============================================================
# 3. NetStim: WHEN ARE EVENTYS GENERATED? gneration of discrete artificial events
# ============================================================

stim = h.NetStim()

stim.start = 100 # first event at 100 ms
stim.number = 3 # number of events generated
stim.interval = 100 # interval between events (ms)

# ============================================================
# 4. NetCon: TRANSMISSION OF EVENTS (WITH DELAY AND WEIGHT)
# ============================================================

nc = h.NetCon(stim,syn)

nc.delay = 10 

# delay between the event generated (NetStim) and the event delivered to synapse (ExpSyn)

#   NetStim generates event at 100 ms
#             |
#             | nc.delay = 10 ms
#             v
#   ExpSyn receives event at 110 ms

nc.weight[0] = 0.001

# This controls the strength of the event delivered to ExpSyn.

# For ExpSyn, an arriving event changes the synaptic conductance.
# Larger weight -> larger conductance change -> generally larger PSP.

nc.threshold = 10

# NetCon can detect events from a voltage-based presynaptic source.
# In that situation, threshold specifies the voltage at which the
# source is considered to have generated an event.

# Example:
#
#   presynaptic neuron voltage
#              |
#              | crosses threshold
#              v
#           NetCon
#              |
#              v
#            ExpSyn
#
# HOWEVER, our source is NetStim:
#
#       NetStim -> NetCon -> ExpSyn
#
# NetStim already generates discrete events, so start/number/interval
# control their timing. Changing threshold is NOT how you control
# the timing of these NetStim events.
#
# Threshold becomes much more useful later when we use:
#
#       presynaptic neuron -> NetCon -> ExpSyn

# ============================================================
# 5.Record
# ============================================================

t = h.Vector()
v = h.Vector()

t.record(h._ref_t)
v.record(soma(0.5)._ref_v)

# ============================================================
# 6. Run NEURON simmulation
# ============================================================

h.finitialize(-65)
h.continuerun(300)

time = list(t)
voltage = list(v)

# ============================================================
# 7. Calculate Event Times
# ============================================================

generated_events = [stim.start + i * stim.interval for i in range(int(stim.number))]
# loop through the events generated by NetStim

arrival_events = [event_time + nc.delay for event_time in generated_events]


# ============================================================
# 8. Plot
# ============================================================

plt.figure(figsize=(10, 5))
plt.plot(time, voltage, label="Postsynaptic voltage")

for i, x in enumerate(generated_events):
    plt.axvline(
        x,
        linestyle="--",
        alpha=0.4,
        label="NetStim event" if i == 0 else None
    )

for i, x in enumerate(arrival_events):
    plt.axvline(
        x,
        linestyle=":",
        alpha=0.8,
        label="ExpSyn receives event" if i == 0 else None
    )

plt.xlabel("Time (ms)")
plt.ylabel("Membrane voltage (mV)")
plt.title("NetStim → NetCon → ExpSyn: event timing and PSPs")
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.show()

# ============================================================
# 9. Print Parameters and Times
# ============================================================

print("\n===== EVENT TIMING =====")

print("NetStim generates:")
for x in generated_events:
    print(f"  {x:.1f} ms")

print("\nExpSyn receives after NetCon delay:")
for x in arrival_events:
    print(f"  {x:.1f} ms")

print("\n===== PARAMETERS =====")
print(f"stim.start    = {stim.start} ms")
print(f"stim.number   = {stim.number}")
print(f"stim.interval = {stim.interval} ms")
print(f"nc.delay      = {nc.delay} ms")
print(f"nc.weight[0]  = {nc.weight[0]}")
print(f"nc.threshold  = {nc.threshold} mV")
print(f"syn.tau       = {syn.tau} ms")
print(f"syn.e         = {syn.e} mV")




"""    NETSTIM
    "When do I generate events?"
       |
       | start / number / interval
       v
    NETCON
    "How do I transmit them?"
       |
       | delay / weight
       | threshold* 
       v
    EXPSYN
    "What does the synapse do?"
       |
       | tau / e
       v
    POSTSYNAPTIC MEMBRANE
    "How does the neuron respond?"

    * threshold is particularly important when NetCon is listening
      to a presynaptic voltage rather than a NetStim."""